### DISCUSSION TITLE
Announcement: New Features WebDAV and OpenDAL in upcoming rustic version

### DISCUSSION THREAD

**Discussion by simonsan** [rustic-rs/rustic#1029] [Announcements]
### Dear `rustic` and `restic` community,

The next rustic version, which will be released soon, will bring two major innovations.  
On the one hand, we have integrated `OpenDAL`.  
On the other hand, you can now spawn a WebDAV server with `rustic webdav`, which gives you access to the snapshots in your repository in the file browser.

To make sure that everything works properly with your configurations, please download [rustic-nightly](https://github.com/rustic-rs/nightly?tab=readme-ov-file#download-matrix) and test it with your use case.

# OpenDAL? Tell me more!

OpenDAL is a data access layer that allows users to easily and efficiently retrieve data from various storage services in a unified way.  
For `rustic` the integration of OpenDAL means, that we are supporting a wide range of [backends](https://opendal.apache.org/docs/category/services/) now.

For example, S3 support has been added directly into rustic, as it seems very mature.  
All other opendal supported services are available via the `opendal:<SERVICE>` syntax in the config file.  
Services supported by OpenDAL and their current implementation status you can find [here](https://opendal.apache.org/docs/category/services/).

If you wanted to try out B2 for example, you can use `opendal:b2` in the repository string and set the needed config options within the `[repository.options]` part of the rustic config file:

```toml  
[repository]  
repository = "opendal:b2"

[repository.options]  
root = "..." # Set the work directory for backend  
key_id = "..." # B2 application key keyID  
application_key = "..." # B2 application key applicationKey  
bucket = "..." # B2 bucket name  
bucket_id = "..." # B2 bucket_id  
```

# WebDAV

With `rustic webdav` you can spawn a WebDAV server to get access to your snapshots and their files via the file browser.  
The [config docs](https://github.com/rustic-rs/rustic/tree/main/config#webdav-options) contain the settings you can use in the config to refine your experience.  
And we have added an [example](https://github.com/rustic-rs/rustic/blob/a6ec35680fb4b03a698ba3af1aaab9c23ea8d072/config/full.toml#L173) configuration.

# Debug

It may make sense to run `rustic` with debug flags enabled via:

```toml  
[global]  
log-level = "debug"  
```

Please let us know if you experience anything unusual.

Cheers,  
the rustic Maintainers
