### DISCUSSION TITLE
Cannot restore from rclone repo if hot-repo has been removed

### DISCUSSION THREAD

**Discussion by AlphaJack** [rustic-rs/rustic#1086] [Q&A] [answered]
I am trying to restore a rclone repo using restore. This is my configuration:

```toml
[repository]
repository = "rclone:remote:/Test"
repo-hot = "local:/home/jack/Desktop/backup/Test"
cache-dir = "local:/home/jack/Desktop/cache/Test"
password = "XXXXXX"

[repository.options]
rclone-command = "rclone --config /home/jack/Desktop/rclone.conf serve restic --addr localhost:0"
use-password = "true"

[global.env]
RCLONE_CONFIG_PASS = "YYYYYY"

[[backup.sources]]
source = "/home/jack/Desktop/Test"
```

I run the following commands:

```bash
rustic -P Test init
rustic -P Test backup
rustic -P Test restore latest /home/jack/Desktop/restore
```

and they work, but if I then run

```bash
rm -r /home/jack/Desktop/restore
rm -r /home/jack/Desktop/backup/Test
rustic -P Test restore latest /home/jack/Desktop/restore
```

I receive the following error:

```
error: keys from repo and repo-hot do not match for rclone:remote:/Test#local:/home/jack/Desktop/backup/Test. Aborting.
```

The same happens if I try to run a second `rustic backup`, after the hot-repo has been removed

What can I do in case my hard drive with the hot repo breaks down and I only have the cold rclone repo available?

Should I do something with the output "[INFO] key 2797cd8f successfully added." of the init command?
