### DISCUSSION TITLE
Configure Scaleway Glacier Backup

### DISCUSSION THREAD

**Discussion by Modrizen** [rustic-rs/rustic#1211] [Q&A] [answered]
Hi, I am trying to configure a backup to Scaleway glacier but encountering this error
`
error: backend openDAL Backend cannot be loaded: Unsupported (permanent) at , context: { scheme: s3:https://s3.fr-par.scw.cloud/coldbucket} => scheme is not enabled or supported
`
 
Here my configuration file
``` toml
[repository]
repository = "opendal:s3"
repo-hot = "opendal:s3"
password = "*********"

[repository.options-cold]
bucket = "coldbucket"
region = "fr-par"
root = '/'
default-storage-class = "GLACIER"
access_key_id = "*************"
secret_access_key = "**********************"

[repository.options-hot]
bucket = "hotbucket"
region = "fr-par"
root = '/'
default-storage-class = "STANDARD"
access_key_id = "*************"
secret_access_key = "**********************"
```

There the command i used for init
``` bash
 rustic -r opendal:s3:https://s3.fr-par.scw.cloud/coldbucket --repo-hot opendal:s3:https://s3.fr-par.scw.cloud/hotbucket init 
```
I can't remember all the things I tried, but every time I had this error or that one 

```
error: Matching variant not found
```

I've seen this issue but it doesn't seem to be the same problem.
[https://github.com/rustic-rs/rustic/issues/1161](https://github.com/rustic-rs/rustic/issues/1161)
