### DISCUSSION TITLE
Minio as cold storage provider - InvalidStorageClass

### DISCUSSION THREAD

**Discussion by benjaminpreiss** [rustic-rs/rustic#1406] [Q&A] [answered]
Hey there!

I am trying to test a cold storage setup locally with minio, with the following rustic.toml config:

```toml
[repository]
repository = "opendal:s3"
repo-hot = "/persisted/rustic/repo_hot"
password = "your_encryption_password_here"
cache-dir = "/persisted/rustic/cache"

# options only for hot part
[repository.options-hot]

# options only cold part
[repository.options-cold]
bucket = "test-2"
root = "/backups"
# currently only default_storage_class = "STANDARD" works
default_storage_class = "DEEP_ARCHIVE"
endpoint = "http://minio:9000"
access_key_id = "rustic-user"
secret_access_key = "rustic-password"
region = "us-east-1"
```

This is quite obvious, as minio is not a cold storage provider.
So I wonder if I can run a rustic "cold storage" repo with storage class "STANDARD" and what the implications of that are for restores? Will rustic still run "restore" operations for files, or will it just access them?

Would be very grateful for insights on the topic, as I have a storage provider that provides me cold storage on top of minio. I reckon they provide the minio `restore` operation (https://min.io/docs/minio/linux/reference/minio-mc/mc-ilm-restore.html) to transition objects into a retrievable state.
