### DISCUSSION TITLE
Restore fails silently hot+cold

### DISCUSSION THREAD

**Discussion by benjaminpreiss** [rustic-rs/rustic#1440] [Q&A]
On my cold backup set up, my restore fails silently, immediately after the following message:

`[INFO] total restore size: 50.0 MiB`

This is my config file:

```toml
[repository]
repository = "opendal:s3"
repo-hot = "/persisted/rustic/repo_hot"
password = "$RUSTIC_ENCRYPTION_PASSWORD"
cache-dir = "/persisted/rustic/cache"
warm-up = true

# options only for hot part
[repository.options-hot]

# options only cold part
[repository.options-cold]
bucket = "$REMOTE_BUCKET_NAME"
root = "$REMOTE_PATH"
default_storage_class = "$REMOTE_STORAGE_CLASS"
endpoint = "$REMOTE_ENDPOINT"
access_key_id = "$REMOTE_ACCESS_KEY_ID"
secret_access_key = "$REMOTE_SECRET_ACCESS_KEY"
region = "$REMOTE_REGION"
```

Could this be due to warm-up-wait not being set?
Or why am I not getting an error message?
If so, would setting warm-up-wait be better in showing me an error message?

Also, looking at this [discussion](https://github.com/rustic-rs/rustic/discussions/1430), I wonder if I then need to know exactly how long the warm-up time will be... What if the warm-up time varies?
