### ISSUE TITLE
error sanitizing source with whitespaces in config file

### ISSUE THREAD

**Issue by AlphaJack** [rustic-rs/rustic#1094]
#558 

I have a folder with whitespace that I would like to backup:

```toml
[[backup.sources]]
source = "/home/jack/Mobile Backup"
```

CLI output:
```
[00:00:00] reading index...               ████████████████████████████████████████          0/0                                                       
[WARN] error sanitizing source="/home/jack/Mobile Backup" in config file
```

Escaping with a backslash works only if I use single quotes:

```toml
[[backup.sources]]
source = '/home/jack/Mobile\ Backup'
```
CLI output:
```
[00:00:00] reading index...               ████████████████████████████████████████          0/0                                                       
[00:00:00] getting latest snapshot...     ████████████████████████████████████████          0/0                                                       
[00:00:17] backing up...
```

But it doesn't work with double quotes:

```toml
[[backup.sources]]
source = "/home/jack/Mobile\ Backup"
```
CLI output:
```
error: rustic-rs fatal error: parse error: invalid escape character in string: ` ` at line 8 column 46
```

In the [full configuration file example](https://github.com/rustic-rs/rustic/blob/6fffaad1cc1aeebf874063fc62125f4ce3b490b5/config/full.toml#L115C1-L115C93) it is said that `source` can contain multiple path in a string, separated by a whitespace, and I think this is the cause of the issue.

Why not having `sources` as an array of `source`, as `password-command` is an alternative to `password`?
