### ISSUE TITLE
`error: Matching Variant not found` when repository is in format "D:/Repo" instead of "D:\\Repo"

### ISSUE THREAD

**Issue by AlphaJack** [rustic-rs/rustic#1104]
This is my Windows configuration:

```toml
[repository]
repository = "D:/Backup/rustic/Test"
password = "XXXXXX"

[[backup.sources]]
source = "C:/Users/Jack/Desktop/Test"
```

When I launch `rustic --log-level trace -P "C:/Users/Jack/Desktop/testconf" init`, I receive this:

```
[INFO] Using config C:/Users/Jack/Desktop/testconf.toml
error: Matching Variant not found
```

I tried the following combinations:

| Repo | Source | Result |
| -- | -- | -- |
| `repository = "D:/Backup"` | `source = "C:/Test"` |  "error: Matching Variant not found" |
| `repository = "/D/Backup"` | `source = "C:/Test"` |  `init` at `C:\D\Backup`, `backup` ok |
| `repository = "D:\\Backup"` | `source = "C:\\Test"` |  `init` ok, `backup` cannot find files |
| `repository = "D:\\Backup"` | `source = "C:/Test"` |  `init` ok, `backup` ok |

Why it is not possible to use `repository = "D:/Backup"`?
