### ISSUE TITLE
TOML Files No Longer Parsed Correctly Starting From v0.9.0

### ISSUE THREAD

**Issue by ossie-git** [rustic-rs/rustic#1420]
The latest versions of rustic (v.0.9.0+) tail to parse valid TOML files. Taking the example from [here](https://rustic.cli.rs/docs/commands/init/configuration_file.html), we have the following:

```toml
[repository]
repository = "/backup/rustic"
password-file = "/root/key-rustic"
no-cache = true # no cache needed for local repository

[forget]
keep-daily = 14
keep-weekly = 5

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
glob-file = ["/root/rustic-local.glob"]

[[backup.sources]]
source = "/home"
git-ignore = true

[[backup.sources]]
source = "/etc"
```

Running `check` fails:

```
$ rustic check -P official_example
error: rustic-rs fatal error: parse error: TOML parse error at line 14, column 1
   |
14 | [[backup.sources]]
   | ^^^^^^^^^^^^^^^^^^
invalid type: map, expected a string
```

Meanwhile, older versions (v0.8.1 and below) parsed the above file without issue:

```
[INFO] using config /home/vagrant/.config/rustic/official_example.toml
error: error opening password file `Os { code: 13, kind: PermissionDenied, message: "Permission denied" }`
```
