### ISSUE TITLE
git-ignore option has a lower priority than whitelist glob

### ISSUE THREAD

**Issue by istudyatuni** [rustic-rs/rustic#691]
As title says. I think when `git-ignore: true`, it should be higher priority than glob

```toml
# ~/.config/rustic/test.toml
[repository]
repository = "/tmp/rustic-test/repo"
password = "a"

[[backup.sources]]
source = "/tmp/rustic-test/dir"
git-ignore = true
glob = [
    "!*",
    "/tmp/rustic-test/dir/*",
]
```
repro:
```sh
rustic -P test init
cd /tmp/rustic-test
mkdir dir && cd dir
touch {a,b}.txt
echo 'a.txt' > .gitignore
rustic -P test backup
rustic -P test snapshots  # get snapshot id

rustic -P test ls $snapshot_id
"tmp"
"tmp/rustic-test"
"tmp/rustic-test/dir"
"tmp/rustic-test/dir/.gitignore"
"tmp/rustic-test/dir/a.txt"  # <- this file in gitignore
"tmp/rustic-test/dir/b.txt"
```

maybe #687 is related
