### ISSUE TITLE
Include and exclude globs cause all files to be ignored in backup

### ISSUE THREAD

**Issue by DianaNites** [rustic-rs/rustic#707]
I'm trying to exclude some directories from my backup, and using globs to do so per [this discussion](https://github.com/rustic-rs/rustic/discussions/636)

Using any include glob causes every single file to be ignored in the backup, but leaves directories. It will report `Files:       0 new, 0 changed, 0 unchanged` and the resulting snapshot reports 0 files, however many dirs it found, and 0 bytes size.

The behavior does not depend on the order of the globs.

My use-case for this is I want to ignore a large directory, steam games, by "default". But some games store their saves next to them, so they need to be backed up. The behavior I expect is that explictly providing a path later in the list will "override" or "inject" it, ignoring the exclusion. I explictly put it there, after all.

Writing this I've realized that adding it as an entirely separate backup source kind of achieves this, but then as i understand it, it would create a *ton* of disconnect snapshots for all the different paths and generally be rather annoying and unwieldy, as well as very verbose?

<details>
<summary>config</summary>

```toml
[[backup.sources]]
source = "/some/path"
glob = [
    "!/some/path/to/exclude",

"/some/path/to/exclude/some/exception",

# Or

    "/some/exception",
]
```

</details>

----

System

`rustic 0.5.4`
`6.3.9-arch1-1`
